name: Build generic resume example

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v4
      - run: typst compile --root . examples/generic/resume.typ examples/generic/resume.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: generic-resume
          path: examples/generic/resume.pdf
